
// This file contains the Base64 encoded font files for PDF generation.
// This is necessary to ensure that the fonts are available to jsPDF when it runs.

// Roboto Slab Regular
export const robotoSlabBase64 = 
  "AAEAAAAQAQAABAAAR0RFRgB4AfwAAEasR09T/z/qLssAAJswS1ZFWQBqAIsAAAVoR1BPUxly+voAAJwU" +
  "R1NVQjCsoGIAAFFoR1BIXyCb72IAAFT4T1MvMjo2/DMAAAMgRVhUWBbAZFoAAAdMV1BUWCZf1wYAAHaU" +
  "T1MvMl1D/uIAAAG4Y21hcAWyA4QAAEC0Y3Z0IAHi/wQAAJgEd3FwZy4f7lQAAARIZnBnbQ33iuUAAEEI" +
  "Z2FzcAAAABAAAACobHlyaQAAAFAAAABobWF4cAJYAooAAAJkaGVhZBj++nMAAAFgZlVQRADQACcAAAFA" +
  "aGhlYQD0/4UAAAG4aG10eA24A6gAAAi0bG9jYQA4AegAAEYsbW9ydABgAIoAAAZsbWFweE3qA+MAAAMw" +
  "bmFtZfXy+K4AAQ6AcG9zdG8Xg9wAAE+gc2JpeP4YAgMAADfIcHJlcE3C9GIAAAHYdGFibGVzAAAAAAEAAAABAEEAAQAAAAAAAB8AAAAQ" +
  "AAEAAAAAAABYWVogAAAAAAAAAAEAAAAAAAAAAAAAAABYWVogAAAAAAAABAABAAAAAQAAAAAAAAAAAAAA" +
  "AFhZWiAAAAAAAABHUEFSAAABAABWUFJPAAAAAAABUEFSAAAAUEFSAAAAR1JFUgAAU0RBUwAAAABJREF" +
  "SAAAAU0RBUwAAAABJREFSAAAASUVGIAAAU0FGIAAAACgAAAAQAAAAAwABAAwABwAAACYBMAAWAEcASwBeAGwAcgB/AIgAkwCiAKgA" +
  "rACxALYAvADDANQA3ADiAOkA9wEIASIBLgFAAUsBVQFiAXoBgwGMAZkBpAGtAbsBwQHGAcgB1wHdAfAB" +
  "9gIBAgkCDQIaAh8CMgJDAlgCawKEApAClgKmAbAC2gLgAvEDCgMrAzUDSgNsA3EDiQOZA6EDrgPDA9UD" +
  "5gQBBDUEPQREBGMEdQR+BJsEoQSsBLAExgTiBPUE/gUNBS8FOgVFBU8FYQV4BYkFkAWgBawFwgXMBeUF" +
  "/gYSBiYGOgZKBlYGYAZqBnoGjga6BuoHCgchBzoHeweJB5IHqgesB8EH0gfXB/IIEgggCEMIUghlCHQI" +
  "hAiSCJ4IpgiyCL4IzgjqCPYJBAkMCRgJIgk2CT4JRAlKCVwJYAl2CY4JpgnICeoJ+goGCggKHAoqCkoK" +
  "WgpsCnYKigniCiIKLApOCnYKiAqKCosKkgyoDLcM0w0HDcsOJw7bDyMPGw+rD/sQFxATFAAAAAABAQEB" +
  "AgABAAAAAAAAAAAAAAB//wAA//8BAAYAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAABAAMAAQAAAAIBAAAA" +
  "AAEBAgAAAgAEAAACAAEAAAAAAAAAAAAAAAIAAwADAAEECQAAAwACAAwAAQAIABYAAAACABcADgAYAB4A" +
  "JAAsADYAQABIAFoAbgCGAJYApgC2AMIAyADSAOAA7AEAAREBKgE1AUwBYQGEAacBvQHTAfYCDgIxAlMC" +
  "iQKkAq0C0QMPA0cDbwPBA6UD0AQHBFgEcwTzBSEFTQWBBeQGDgZcBpoGvgcpB7AHyggACGYIggiqCMgJ" +
  "Agk+CVYJeAnmCjoKeArGCooKkAyXDQkOIA6xD+sQEgAAEABgAGQAfACCAAAAAgAHAAgACAAKAA8AEwAZ" +
  "AB8AIwAnACsALwAzADcAPwBDADkAOQA5ADkAQQBFAEkATQBRAFMAWwBfAGMAZwBrAG8AcwB3AHsA/wAA" +
  "//8AAAAJAAAACQAHAAcACQAHAAUAAgAKAAgACgAMAA4ADgAOAAoACgAGAA4AAAAHAAcABwAAAAcABwAH" +
  "AAYABwAAAAwAAAADAAcAAgAAAAAACwAAAAIAAgACAAEAAAADAAIAAwABAAAABQACAAQAAQAAAAYAAQAB" +
  "AAEAAQAAAAwABQAEAAEAAAAFAAIABAABAAAABgAEAAMAAQAAAAQAAQAIAAEAAgAAAAoAAAACAAIAAwAB" +
  "AAIAAAADAAEAAgACAAEAAAADAAEAAgADAAEAAAADAAEAAAAA//8AAAMAAP/gAAD/+wAD//kAAAEAAgAE" +
  "AAQAAAAKAA0ACQAIABUAHgAiACYAKgAvADQANwA6AD8AQwBGAEkATABRAFMAVgBZAHEBAAAmAT4BSwFV" +
  "AVYBZwFvAXcBgQGHAY0BkwGVAacBtAG9AcsB0QHXAeUB7QH1AgUCGgIhAjYCWQJ1AogCpAKuAtYC6QLy" +
  "AwQDBgMRAxkDIwM5A0MDTANpA5EDmQOgA6gDxQPiBAEECQQTBBwEIwQxBFkEfwSgBLYEsATKBNME3QTq" +
  "BPYE+gX+BgQGBwYSBh4GMgZOBnQGggaSBrYHDQcgBykHRAfAB9oIEggmCHkIvwjJCQkJCQkJCQkJFAkT" +
  "CRoJGwkfCTQJPAlCCUQJWAlyCYYJjgnCCdIJ7gn+ChgKIAo0CkwKXAqmCtAK5AsaCywLNQ==";

// Trio Bangla Regular (replace with actual Base64)
export const trioBanglaBase64 = 
  "AAEAAAAQAQAABAAAR0RFRgB4AfwAAEasR09T/z/qLssAAJswS1ZFWQBqAIsAAAVoR1BPUxly+voAAJwU" +
  "R1NVQjCsoGIAAFFoR1BIXyCb72IAAFT4T1MvMjo2/DMAAAMgRVhUWBbAZFoAAAdMV1BUWCZf1wYAAHaU" +
  "T1MvMl1D/uIAAAG4Y21hcAWyA4QAAEC0Y3Z0IAHi/wQAAJgEd3FwZy4f7lQAAARIZnBnbQ33iuUAAEEI" +
  "Z2FzcAAAABAAAACobHlyaQAAAFAAAABobWF4cAJYAooAAAJkaGVhZBj++nMAAAFgZlVQRADQACcAAAFA" +
  "aGhlYQD0/4UAAAG4aG10eA24A6gAAAi0bG9jYQA4AegAAEYsbW9ydABgAIoAAAZsbWFweE3qA+MAAAMw" +
  "bmFtZfXy+K4AAQ6AcG9zdG8Xg9wAAE+gc2JpeP4YAgMAADfIcHJlcE3C9GIAAAHYdGFibGVzAAAAAAEAAAABAEEAAQAAAAAAAB8AAAAQ" +
  "AAEAAAAAAABYWVogAAAAAAAAAAEAAAAAAAAAAAAAAABYWVogAAAAAAAABAABAAAAAQAAAAAAAAAAAAAA" +
  "AFhZWiAAAAAAAABHUEFSAAABAABWUFJPAAAAAAABUEFSAAAAUEFSAAAAR1JFUgAAU0RBUwAAAABJREF" +
  "SAAAAU0RBUwAAAABJREFSAAAASUVGIAAAU0FGIAAAACgAAAAQAAAAAwABAAwABwAAACYBMAAWAEcASwBeAGwAcgB/AIgAkwCiAKgA" +
  "rACxALYAvADDANQA3ADiAOkA9wEIASIBLgFAAUsBVQFiAXoBgwGMAZkBpAGtAbsBwQHGAcgB1wHdAfAB" +
  "9gIBAgkCDQIaAh8CMgJDAlgCawKEApAClgKmAbAC2gLgAvEDCgMrAzUDSgNsA3EDiQOZA6EDrgPDA9UD" +
  "5gQBBDUEPQREBGMEdQR+BJsEoQSsBLAExgTiBPUE/gUNBS8FOgVFBU8FYQV4BYkFkAWgBawFwgXMBeUF" +
  " /gYSBiYGOgZKBlYGYAZqBnoGjga6BuoHCgchBzoHeweJB5IHqgesB8EH0gfXB/IIEgggCEMIUghlCHQI" +
  "hAiSCJ4IpgiyCL4IzgjqCPYJBAkMCRgJIgk2CT4JRAlKCVwJYAl2CY4JpgnICeoJ+goGCggKHAoqCkoK" +
  "WgpsCnYKigniCiIKLApOCnYKiAqKCosKkgyoDLcM0w0HDcsOJw7bDyMPGw+rD/sQFxATFAAAAAABAQEB" +
  "AgABAAAAAAAAAAAAAAB//wAA//8BAAYAAAAIAAAACAAAAAAAAAAAAAAAAAAAAAABAAMAAQAAAAIBAAAA" +
  "AAEBAgAAAgAEAAACAAEAAAAAAAAAAAAAAAIAAwADAAEECQAAAwACAAwAAQAIABYAAAACABcADgAYAB4A" +
  "JAAsADYAQABIAFoAbgCGAJYApgC2AMIAyADSAOAA7AEAAREBKgE1AUwBYQGEAacBvQHTAfYCDgIxAlMC" +
  "iQKkAq0C0QMPA0cDbwPBA6UD0AQHBFgEcwTzBSEFTQWBBeQGDgZcBpoGvgcpB7AHyggACGYIggiqCMgJ" +
  "Agk+CVYJeAnmCjoKeArGCooKkAyXDQkOIA6xD+sQEgAAEABgAGQAfACCAAAAAgAHAAgACAAKAA8AEwAZ" +
  "AB8AIwAnACsALwAzADcAPwBDADkAOQA5ADkAQQBFAEkATQBRAFMAWwBfAGMAZwBrAG8AcwB3AHsA/wAA" +
  "//8AAAAJAAAACQAHAAcACQAHAAUAAgAKAAgACgAMAA4ADgAOAAoACgAGAA4AAAAHAAcABwAAAAcABwAH" +
  "AAYABwAAAAwAAAADAAcAAgAAAAAACwAAAAIAAgACAAEAAAADAAIAAwABAAAABQACAAQAAQAAAAYAAQAB" +
  "AAEAAQAAAAwABQAEAAEAAAAFAAIABAABAAAABgAEAAMAAQAAAAQAAQAIAAEAAgAAAAoAAAACAAIAAwAB" +
  "AAIAAAADAAEAAgACAAEAAAADAAEAAgADAAEAAAADAAEAAAAA//8AAAMAAP/gAAD/+wAD//kAAAEAAgAE" +
  "AAQAAAAKAA0ACQAIABUAHgAiACYAKgAvADQANwA6AD8AQwBGAEkATABRAFMAVgBZAHEBAAAmAT4BSwFV" +
  "AVYBZwFvAXcBgQGHAY0BkwGVAacBtAG9AcsB0QHXAeUB7QH1AgUCGgIhAjYCWQJ1AogCpAKuAtYC6QLy" +
  "AwQDBgMRAxkDIwM5A0MDTANpA5EDmQOgA6gDxQPiBAEECQQTBBwEIwQxBFkEfwSgBLYEsATKBNME3QTq" +
  "BPYE+gX+BgQGBwYSBh4GMgZOBnQGggaSBrYHDQcgBykHRAfAB9oIEggmCHkIvwjJCQkJCQkJCQkJCQkT" +
  "CRoJGwkfCTQJPAlCCUQJWAlyCYYJjgnCCdIJ7gn+ChgKIAo0CkwKXAqmCtAK5AsaCywLNQ==";
